# Generated by Django 5.0.6 on 2024-08-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="courses",
            new_name="course_name",
        ),
    ]
