# Generated by Django 5.0.6 on 2024-08-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_courses_courses_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcements",
            old_name="announcements",
            new_name="announcement_name",
        ),
        migrations.RenameField(
            model_name="assignments",
            old_name="assignments",
            new_name="assignment_name",
        ),
        migrations.AlterField(
            model_name="announcements",
            name="date",
            field=models.DateTimeField(auto_now_add=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="assignments",
            name="date",
            field=models.DateTimeField(auto_now_add=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="courses",
            name="date",
            field=models.DateTimeField(auto_now_add=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="date",
            field=models.DateTimeField(auto_now_add=True, max_length=200),
        ),
    ]
